#!/usr/bin/node
var extend = require('extend');
var fs=require("fs");
var myarg = process.argv;
myarg.splice(0,2);
var filein = myarg[0];
var fileout = myarg[1];
if (filein === undefined || filein == "" || fileout === undefined || fileout == ""){
	console.log("Usage : fail2ban-log FILEIN FILEOUT ");
	process.exit(1);
}
console.log("File in "+filein);
console.log("File out "+fileout);
var geojson;
try {
	var content = fs.readFileSync(fileout, 'utf8');
	if (content == "" || content === undefined){
		console.log("Init geojson");
		geojson = {type: "FeatureCollection", features: []};
	} else {
		geojson = JSON.parse(content);
	}
} catch (e) {
	console.log("Fail to parse fileout");
	process.exit(1);
}

require('./src/fail2ban-log')(filein,function(err,newgeojson){
	fs.writeFileSync(fileout,JSON.stringify({type: "FeatureCollection", features:geojson.features.concat(newgeojson.features)}),'utf8');
})